/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentePresentacion;

import componenteEntidad.Alumno;
import componenteEntidad.Apoderado;
import componenteNegocio.AlumnoCN;
import componenteNegocio.ApoderadoCN;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JhordyAlexi
 */
public class dialogAlumnoo extends javax.swing.JDialog {

    /**
     * Creates new form dialogAlum
     */
    boolean reg;
    Apoderado idApoderado;
    Apoderado apoderadoSelec01 = new Apoderado();
    public dialogAlumnoo() {
        super(FrmPrincipal.getInstancia(), true);
        initComponents();
        limpiarTextos();
        textos(false);
        controles(true);
        limpiarTextosAlumnos();
        textosAlumnos(false);
        controleAlumnos(true);
        setLocationRelativeTo(null);
    }

    void limpiarTextos(){
        txtidApoderado.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtTelefono.setText("");
        cboEstadoCivil.setSelectedIndex(0);
        txtDireccion.setText("");
    }
    void textos(boolean tf){
        txtidApoderado.setEditable(tf);
        txtNombres.setEditable(tf);
        txtApellidos.setEditable(tf);
        txtTelefono.setEditable(tf);
        cboEstadoCivil.setEnabled(tf);
        txtDireccion.setEditable(tf);
        
    }
    void controles(boolean tf){
        btnNuevo.setEnabled(tf);
        btnRegistrar.setEnabled(!tf);
        btnCancelar.setEnabled(!tf);
        btnModificar.setEnabled(tf);
        btnEliminar.setEnabled(tf);
        btnReporte.setEnabled(tf);
        btnBuscar.setEnabled(tf);
    }
    void limpiarTextosAlumnos(){
        txtidAlumno.setText("");
        txtNombresAlumno.setText("");
        txtApellidosAlumno.setText("");
        txtTelefonoAlumno.setText("");
        cboSexoAlumno.setSelectedIndex(0);
        txtDireccionAlumno.setText("");
        choFechaNacimientoAlumno.setCalendar(null);
    }
    void textosAlumnos(boolean tf){
        txtidAlumno.setEnabled(tf);
        txtNombresAlumno.setEnabled(tf);
        txtApellidosAlumno.setEnabled(tf);
        txtTelefonoAlumno.setEnabled(tf);
        cboSexoAlumno.setEnabled(tf);
        txtDireccionAlumno.setEnabled(tf);
        choFechaNacimientoAlumno.setEnabled(tf);
    }
    void controleAlumnos(boolean tf){
        btnNuevo1.setEnabled(tf);
        btnRegistrar1.setEnabled(!tf);
        btnCancelar1.setEnabled(!tf);
        btnModificar1.setEnabled(tf);
        btnEliminar1.setEnabled(tf);
        btnReporte1.setEnabled(tf);
        btnBuscar1.setEnabled(tf);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidApoderado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboEstadoCivil = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtidAlumno = new javax.swing.JTextField();
        txtNombresAlumno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTelefonoAlumno = new javax.swing.JTextField();
        txtDireccionAlumno = new javax.swing.JTextField();
        choFechaNacimientoAlumno = new com.toedter.calendar.JDateChooser();
        txtApellidosAlumno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cboSexoAlumno = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        btnEliminar1 = new javax.swing.JButton();
        btnNuevo1 = new javax.swing.JButton();
        btnRegistrar1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        btnModificar1 = new javax.swing.JButton();
        btnReporte1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtApellidos1 = new javax.swing.JTextField();
        txtidApoderado1 = new javax.swing.JTextField();
        txtNombres1 = new javax.swing.JTextField();
        btnBuscarApoderado = new javax.swing.JButton();
        btnBuscar1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alumno");

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("GESTIONAR ALUMNO");

        jTabbedPane1.setForeground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Apellidos:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Telefono:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nombres:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Estado Civil:");

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("idApoderado:");

        cboEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Escoger>", "Soltero(a)", "Casado(a)" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Dirección:");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(txtApellidos)
                    .addComponent(jLabel7)
                    .addComponent(cboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(txtidApoderado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres))
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporte)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBuscar, btnCancelar, btnEliminar, btnModificar, btnNuevo, btnRegistrar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(txtidApoderado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo)
                            .addComponent(btnRegistrar)
                            .addComponent(btnCancelar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(btnEliminar)
                            .addComponent(btnModificar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBuscar, btnCancelar, btnEliminar, btnModificar, btnRegistrar});

        jTabbedPane1.addTab("Apoderado", jPanel1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("idAlumno:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Telefono:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Sexo:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Fecha Nacimiento:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Dirección:");

        txtTelefonoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoAlumnoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Apellidos:");

        cboSexoAlumno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Escoger>", "Masculino", "Femenino" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Nombres:");

        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnNuevo1.setText("Nuevo");
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });

        btnRegistrar1.setText("Registrar");
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });

        btnCancelar1.setText("Cancelar");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        btnModificar1.setText("Modificar");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });

        btnReporte1.setText("Reporte");
        btnReporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporte1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Apoderado:"));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("idApoderado:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Apellidos:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Nombres:");

        txtApellidos1.setEditable(false);

        txtidApoderado1.setEditable(false);

        txtNombres1.setEditable(false);

        btnBuscarApoderado.setText("...");
        btnBuscarApoderado.setEnabled(false);
        btnBuscarApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarApoderadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtidApoderado1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarApoderado))
                    .addComponent(txtNombres1)
                    .addComponent(txtApellidos1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtidApoderado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarApoderado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtNombres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtApellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefonoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboSexoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choFechaNacimientoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDireccionAlumno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                .addComponent(txtNombresAlumno, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtApellidosAlumno, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModificar1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnNuevo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnRegistrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCancelar1))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addComponent(btnReporte1)))
                        .addGap(29, 29, 29))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBuscar1, btnCancelar1, btnEliminar1, btnModificar1, btnNuevo1, btnRegistrar1});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtidAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNombresAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtApellidosAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cboSexoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTelefonoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDireccionAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(choFechaNacimientoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo1)
                            .addComponent(btnRegistrar1)
                            .addComponent(btnCancelar1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar1)
                            .addComponent(btnEliminar1)
                            .addComponent(btnBuscar1)))
                    .addComponent(btnReporte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alumno", jPanel2);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtTelefonoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoAlumnoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        if(txtidApoderado.getText().equals("")){
            JOptionPane.showMessageDialog(this, "ingresar un id");
            txtidApoderado.requestFocus();
            return;
        }
        if(txtNombres.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingresar un nombre(s)");
            txtNombres.requestFocus();
            return;
        }
        if(txtApellidos.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingresar un apellido(s)");
            txtApellidos.requestFocus();
            return;
        }
        if(txtTelefono.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingresar un telefono");
            txtTelefono.requestFocus();
            return;
        }
        if(txtDireccion.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingresar una dirección");
            txtDireccion.requestFocus();
            return;
        }
        if(cboEstadoCivil.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Seleccionar un estado civil");
            cboEstadoCivil.requestFocus();
            return;
        }
        String idApoderado = txtidApoderado.getText();
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        String telefono = txtTelefono.getText();
        String direccion = txtDireccion.getText();
        String estadoCivil = cboEstadoCivil.getSelectedItem().toString();
        if(reg){
            try{
                ApoderadoCN.getInstancia().insertar(idApoderado, nombres, apellidos, telefono, direccion, estadoCivil);
                JOptionPane.showMessageDialog(this,"Apoderado registrado."); 
                txtidApoderado1.setText(idApoderado);
                txtNombres1.setText(nombres);
                txtApellidos1.setText(apellidos);
                apoderadoSelec01.setIdApoderado(idApoderado);
                apoderadoSelec01.setNombres(nombres);
                apoderadoSelec01.setApellidos(apellidos);
                apoderadoSelec01.setTelefono(telefono);
                apoderadoSelec01.setDireccion(direccion);
                apoderadoSelec01.setEstadoCivil(estadoCivil);
            }catch(SQLException e){
                System.out.println(e.getMessage());
            }
        }else{
            try{
                ApoderadoCN.getInstancia().actualizar(idApoderado, nombres, apellidos, telefono, direccion, estadoCivil);
                JOptionPane.showMessageDialog(this, "El apoderado se a modificado correctamente..");
            }catch(SQLException e){
                System.out.println(e.getMessage());
            }
        }

        //       try{
            //        Apoderado a = ApoderadoCN.getInstancia().buscarApoderado(idApoderado);
            //                if(a.getIdApoderado().equals(idApoderado)){
                //                    JOptionPane.showMessageDialog(this, "Id repetido, por favor ingrese uno nuevo.");
                //                    return;
                //                }
            //        }catch(SQLException e){
            //                JOptionPane.showMessageDialog(null, e.getMessage());
            //        }
        limpiarTextos();
        textos(false);
        controles(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String idApoderado;
        idApoderado = JOptionPane.showInputDialog("Ingrese Id del apoderado a eliminar:");
        Apoderado apoderado;
        try{
            apoderado = ApoderadoCN.getInstancia().buscarApoderado(idApoderado);
            if(apoderado != null){
                txtidApoderado.setText(apoderado.getIdApoderado());
                txtNombres.setText(apoderado.getNombres());
                txtApellidos.setText(apoderado.getApellidos());
                txtTelefono.setText(apoderado.getTelefono());
                txtDireccion.setText(apoderado.getDireccion());
                cboEstadoCivil.setSelectedItem(apoderado.getEstadoCivil());
                txtidApoderado1.setText("");
                txtNombres1.setText("");
                txtApellidos1.setText("");
                int resp = JOptionPane.showConfirmDialog(this,"Deseas Eliminarlo ","Eliminar Dato",JOptionPane.YES_NO_OPTION );
                if(resp == JOptionPane.YES_OPTION){
                    ApoderadoCN.getInstancia().eliminar(idApoderado);
                    JOptionPane.showMessageDialog(this,"Registro eliminado");
                }
                limpiarTextos();
            }else
            JOptionPane.showMessageDialog(this,"Id apoderado no registrado");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        dialogReporteApoderado reporteApoderado = new dialogReporteApoderado();
        reporteApoderado.setVisible(true);
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        reg=true;
        limpiarTextos();
        textos(true);
        controles(false);
        txtidApoderado.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String idApoderado;
        idApoderado = JOptionPane.showInputDialog("Ingrese Id del apoderado a buscar: ");
        Apoderado  apoderado;
        try{
            apoderado = ApoderadoCN.getInstancia().buscarApoderado(idApoderado);
            if(apoderado != null){
                txtidApoderado.setText(apoderado.getIdApoderado());
                txtNombres.setText(apoderado.getNombres());
                txtApellidos.setText(apoderado.getApellidos());
                txtTelefono.setText(apoderado.getTelefono());
                txtDireccion.setText(apoderado.getDireccion());
                cboEstadoCivil.setSelectedItem(apoderado.getEstadoCivil());
            }else
            JOptionPane.showMessageDialog(this,"Id apoderado no registrado.");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarTextos();
        textos(false);
        controles(true);
        txtidApoderado1.setText("");
        txtNombres1.setText("");
        txtApellidos1.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        String idApoderado;
        idApoderado = JOptionPane.showInputDialog("Ingrese Id del apoderado a modificar: ");
        Apoderado  apoderado;
        try{
            apoderado = ApoderadoCN.getInstancia().buscarApoderado(idApoderado);
            if(apoderado != null){
                txtidApoderado.setText(apoderado.getIdApoderado());
                txtNombres.setText(apoderado.getNombres());
                txtApellidos.setText(apoderado.getApellidos());
                txtTelefono.setText(apoderado.getTelefono());
                txtDireccion.setText(apoderado.getDireccion());
                cboEstadoCivil.setSelectedItem(apoderado.getEstadoCivil());
                reg=false;
                textos(true);
                txtidApoderado.setEnabled(false);
                controles(false);
            }else
            JOptionPane.showMessageDialog(this,"Id apoderado no registrado.");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
        String idAlumno;
        idAlumno = JOptionPane.showInputDialog("Ingrese Id del apoderado a eliminar: ");
        Alumno  alumno;
        try{
            alumno = AlumnoCN.getInstancia().buscarAlumno(idAlumno);
            if(alumno != null){
                txtidApoderado1.setText(alumno.getApoderado().getIdApoderado());
                txtNombres1.setText(alumno.getApoderado().getNombres());
                txtApellidos1.setText(alumno.getApoderado().getApellidos());
                txtidAlumno.setText(alumno.getIdAlumno());
                txtNombresAlumno.setText(alumno.getNombres());
                txtApellidosAlumno.setText(alumno.getApellidos());
                cboSexoAlumno.setSelectedItem(alumno.getSexo());
                txtTelefonoAlumno.setText(alumno.getTelefono());
                txtDireccionAlumno.setText(alumno.getDireccion());
                choFechaNacimientoAlumno.setDate(alumno.getFechaNacimiento());
                int resp = JOptionPane.showConfirmDialog(this,"Deseas Eliminarlo ","Eliminar Dato",JOptionPane.YES_NO_OPTION );
                if(resp == JOptionPane.YES_OPTION){
                    AlumnoCN.getInstancia().eliminar(idAlumno);
                    JOptionPane.showMessageDialog(this,"Registro eliminado");
                }
                limpiarTextosAlumnos();
                txtidApoderado1.setText("");
                txtNombres1.setText("");
                txtApellidos1.setText("");
            }else{
                JOptionPane.showMessageDialog(this,"El id alumno no existe");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        // TODO add your handling code here:
        reg=true;
        limpiarTextosAlumnos();
        textosAlumnos(true);
        controleAlumnos(false);
        txtidAlumno.requestFocus();
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
        // TODO add your handling code here:
        
        if(txtidApoderado1.getText().compareTo("")==0 && txtNombres1.getText().compareTo("")==0
                && txtApellidos1.getText().compareTo("")==0){
            int resp = JOptionPane.showConfirmDialog(this,"Deseas buscar apoderado? ","No se ingreso apoderado",JOptionPane.YES_NO_OPTION );
            if(resp ==JOptionPane.YES_OPTION){
                dialogBuscarApoderado buscarApoderado = new dialogBuscarApoderado();
                buscarApoderado.setVisible(true);
                idApoderado = buscarApoderado.apoderadoSelec;
                txtidApoderado1.setText(idApoderado.getIdApoderado());
                txtNombres1.setText(idApoderado.getNombres());
                txtApellidos1.setText(idApoderado.getApellidos());
                idApoderado.getTelefono();
                idApoderado.getDireccion();
                idApoderado.getEstadoCivil();
            }
            return;
        }
        if(txtidAlumno.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingresar id");
            txtidAlumno.requestFocus();
            return;
        }
        if(txtNombresAlumno.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingresar un nombre(s)");
            txtNombresAlumno.requestFocus();
            return;
        }
        if(txtApellidosAlumno.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingresar un apellido(s)");
            txtApellidosAlumno.requestFocus();
            return;
        }
        if(cboSexoAlumno.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Seleccioanr sexo");
            cboSexoAlumno.requestFocus();
            return;
        }
        if(txtTelefonoAlumno.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingresar un telefono");
            txtTelefonoAlumno.requestFocus();
            return;
        }
        if(txtDireccionAlumno.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingresar una direccion");
            txtDireccionAlumno.requestFocus();
            return;
        }
        if(choFechaNacimientoAlumno.getCalendar()==null){
            JOptionPane.showMessageDialog(this, "Ingresar una fecha de nacimiento");
            choFechaNacimientoAlumno.requestFocusInWindow();
            return;
        }
        String idAlumno = txtidAlumno.getText();
        String nombres = txtNombresAlumno.getText();
        String apellidos = txtApellidosAlumno.getText();
        String sexo = cboSexoAlumno.getSelectedItem().toString();
        String telefono = txtTelefonoAlumno.getText();
        String direccion = txtDireccionAlumno.getText();
        Date fechaNacimiento = choFechaNacimientoAlumno.getDate();
        //Atributos apoderado
        String apod = txtidApoderado1.getText();
        Apoderado bs = new Apoderado();
        try {
            ArrayList<Apoderado> a = ApoderadoCN.getInstancia().mostrarApoderados();
            for(int i=0;i<a.size();i++){
                Apoderado apoderado = a.get(i);
                if(apoderado.getIdApoderado().equals(apod)){
                    bs = ApoderadoCN.getInstancia().buscarApoderado(apod);  
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(dialogAlumnoo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Alumno alumno = new Alumno(idAlumno,bs,sexo,nombres,apellidos,telefono,direccion,fechaNacimiento);
        if(reg){
            try{
                AlumnoCN.getInstancia().insertar(alumno);
                JOptionPane.showMessageDialog(null, "Alumno registrado");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }else{
            try{
                AlumnoCN.getInstancia().actualizar(alumno);
                JOptionPane.showMessageDialog(null, "El Alumno se a modificado correctamente.");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }

        limpiarTextosAlumnos();
        textosAlumnos(false);
        controleAlumnos(true);
        txtidApoderado1.setText("");
        txtNombres1.setText("");
        txtApellidos1.setText("");
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
        limpiarTextosAlumnos();
        textosAlumnos(false);
        controleAlumnos(true);
        txtidApoderado1.setText("");
        txtNombres1.setText("");
        txtApellidos1.setText("");
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
        // TODO add your handling code here:
        String idAlumno;
        idAlumno = JOptionPane.showInputDialog("Ingrese Id del alumno a modificar: ");
        Alumno  alumno;
        btnBuscarApoderado.setText("Modificar?");
        try{
            alumno = AlumnoCN.getInstancia().buscarAlumno(idAlumno);
            if(alumno != null){
                txtidApoderado1.setText(alumno.getApoderado().getIdApoderado());
                txtNombres1.setText(alumno.getApoderado().getNombres());
                txtApellidos1.setText(alumno.getApoderado().getApellidos());
                txtidAlumno.setText(alumno.getIdAlumno());
                txtNombresAlumno.setText(alumno.getNombres());
                txtApellidosAlumno.setText(alumno.getApellidos());
                cboSexoAlumno.setSelectedItem(alumno.getSexo());
                txtTelefonoAlumno.setText(alumno.getTelefono());
                txtDireccionAlumno.setText(alumno.getDireccion());
                choFechaNacimientoAlumno.setDate(alumno.getFechaNacimiento());
                reg=false;
                textosAlumnos(true);
                btnBuscarApoderado.setEnabled(true);
                txtidAlumno.setEnabled(false);
                controleAlumnos(false);
            }else{
                JOptionPane.showMessageDialog(this,"Id Alumno no registrado.");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void btnReporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte1ActionPerformed
        // TODO add your handling code here:
        dialogReporteAlumno reporteAlumno = new dialogReporteAlumno();
        reporteAlumno.setVisible(true);
    }//GEN-LAST:event_btnReporte1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
        String idAlumno;
        idAlumno = JOptionPane.showInputDialog("Ingrese Id del alumno a buscar: ");
        Alumno  alumno;
        try{
            alumno = AlumnoCN.getInstancia().buscarAlumno(idAlumno);
            if(alumno != null){
                txtidApoderado1.setText(alumno.getApoderado().getIdApoderado());
                txtNombres1.setText(alumno.getApoderado().getNombres());
                txtApellidos1.setText(alumno.getApoderado().getApellidos());
                //Atributos alumno
                txtidAlumno.setText(alumno.getIdAlumno());
                txtNombresAlumno.setText(alumno.getNombres());
                txtApellidosAlumno.setText(alumno.getApellidos());
                cboSexoAlumno.setSelectedItem(alumno.getSexo());
                txtTelefonoAlumno.setText(alumno.getTelefono());
                txtDireccionAlumno.setText(alumno.getDireccion());
                choFechaNacimientoAlumno.setDate(alumno.getFechaNacimiento());
            }else{
                JOptionPane.showMessageDialog(this,"Id Alumno no registrado.");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnBuscarApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarApoderadoActionPerformed
        // TODO add your handling code here:
        dialogBuscarApoderado buscarApoderado = new dialogBuscarApoderado();
        buscarApoderado.setVisible(true);
        idApoderado = buscarApoderado.apoderadoSelec;
        txtidApoderado1.setText(idApoderado.getIdApoderado());
        txtNombres1.setText(idApoderado.getNombres());
        txtApellidos1.setText(idApoderado.getApellidos());
        idApoderado.getTelefono();
        idApoderado.getDireccion();
        idApoderado.getEstadoCivil();
    }//GEN-LAST:event_btnBuscarApoderadoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(dialogAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(dialogAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(dialogAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(dialogAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                dialogAlum dialog = new dialogAlum(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscarApoderado;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevo1;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnReporte1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cboEstadoCivil;
    private javax.swing.JComboBox cboSexoAlumno;
    private com.toedter.calendar.JDateChooser choFechaNacimientoAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtApellidos1;
    private javax.swing.JTextField txtApellidosAlumno;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionAlumno;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNombres1;
    private javax.swing.JTextField txtNombresAlumno;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoAlumno;
    private javax.swing.JTextField txtidAlumno;
    private javax.swing.JTextField txtidApoderado;
    private javax.swing.JTextField txtidApoderado1;
    // End of variables declaration//GEN-END:variables
}
