/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentePresentacion;

import componenteDatos.Convertir;
import componenteEntidad.Alumno;
import componenteEntidad.Apoderado;
import componenteNegocio.AlumnoCN;
import componenteNegocio.ApoderadoCN;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JhordyAlexi
 */
public class dialogBuscarAlumno extends javax.swing.JDialog {

    /**
     * Creates new form dialogBuscarApoderado
     */
    DefaultTableModel modelo = new DefaultTableModel();
    String[] nombreColumnas = {"idAlumno","Nombre","Apellido","Sexo","Telefono","Direccion","Fecha Nacimiento"};
    Alumno alumnoSelec = new Alumno();
    public dialogBuscarAlumno() {
        super(FrmPrincipal.getInstancia(), true);
        initComponents();
        setLocationRelativeTo(null);
        txtbuscarAlumno.requestFocus();
        
        modelo.setColumnIdentifiers(nombreColumnas);
        try{
            ArrayList<Alumno> lista = AlumnoCN.getInstancia().mostrarAlumnos();
            Object datos[][]= new Object[lista.size()][7];
            for(int i=0; i<lista.size();i++){
                Alumno alumno = lista.get(i);
                datos[i][0] = alumno.getIdAlumno();
                datos[i][1] = alumno.getNombres();
                datos[i][2] = alumno.getApellidos();
                datos[i][3] = alumno.getSexo();
                datos[i][4] = alumno.getTelefono();
                datos[i][5] = alumno.getDireccion();
                datos[i][6] = alumno.getFechaNacimiento();
                //datos[i][7] = alumno.getApoderado().getNombres();
            }
            modelo.setDataVector(datos, nombreColumnas);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbuscarAlumno = new javax.swing.JTextField();
        btnSeleccionar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Alumno");

        txtbuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarAlumnoActionPerformed(evt);
            }
        });
        txtbuscarAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarAlumnoKeyReleased(evt);
            }
        });

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setToolTipText("Seleccionar un alumno de la lista de alumnos.");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Buscar por Nombre:");

        tabla.setModel(modelo);
        jScrollPane2.setViewportView(tabla);

        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnTodos.setText("Todos");
        btnTodos.setToolTipText("Muestra todos los alumnos registrados.");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Buscar Alumno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(256, 256, 256))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbuscarAlumno)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSeleccionar)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTodos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalir)))
                        .addGap(84, 84, 84))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBuscar, btnSalir, btnTodos});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtbuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTodos)
                        .addComponent(btnSalir))
                    .addComponent(btnSeleccionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarAlumnoActionPerformed
        // TODO add your handling code here

    }//GEN-LAST:event_txtbuscarAlumnoActionPerformed

    private void txtbuscarAlumnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarAlumnoKeyReleased
        // TODO add your handling code here:
        String nombre=txtbuscarAlumno.getText();

        modelo.setColumnIdentifiers(nombreColumnas);
        try {
            ArrayList<Alumno> lista = AlumnoCN.getInstancia().buscarPorNombre(nombre);
            Object [][]datos=new Object[lista.size()][8];
            for (int i = 0; i < lista.size(); i++) {
                Alumno alumno = lista.get(i);
                datos[i][0] = alumno.getIdAlumno();
                datos[i][1] = alumno.getNombres();
                datos[i][2] = alumno.getApellidos();
                datos[i][3] = alumno.getSexo();
                datos[i][4] = alumno.getTelefono();
                datos[i][5] = alumno.getDireccion();
                datos[i][6] = alumno.getFechaNacimiento();
                datos[i][7] = alumno.getApoderado().getNombres();
            }
            modelo.setDataVector(datos, nombreColumnas);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_txtbuscarAlumnoKeyReleased

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        int i = tabla.getSelectedRow();
        if(i != -1) {
            alumnoSelec.setIdAlumno(modelo.getValueAt(i, 0).toString());
            alumnoSelec.setNombres(modelo.getValueAt(i, 1).toString());
            alumnoSelec.setApellidos(modelo.getValueAt(i, 2).toString());
            alumnoSelec.setSexo(modelo.getValueAt(i, 3).toString());
            alumnoSelec.setTelefono(modelo.getValueAt(i, 4).toString());
            alumnoSelec.setDireccion(modelo.getValueAt(i, 5).toString());
            alumnoSelec.setFechaNacimiento(Date.valueOf(modelo.getValueAt(i, 6).toString()));
            //alumnoSelec.setNombres(modelo.getValueAt(i, 7).toString());
            
            this.dispose();
        } else
        JOptionPane.showMessageDialog(null, "Debes Seleccionar un elemento");
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
         String nombre=txtbuscarAlumno.getText();

        modelo.setColumnIdentifiers(nombreColumnas);
        try {
            ArrayList<Alumno> lista = AlumnoCN.getInstancia().buscarPorNombre(nombre);
            Object [][]datos=new Object[lista.size()][8];
            for (int i = 0; i < lista.size(); i++) {
                Alumno alumno = lista.get(i);
                datos[i][0] = alumno.getIdAlumno();
                datos[i][1] = alumno.getNombres();
                datos[i][2] = alumno.getApellidos();
                datos[i][3] = alumno.getSexo();
                datos[i][4] = alumno.getTelefono();
                datos[i][5] = alumno.getDireccion();
                datos[i][6] = alumno.getFechaNacimiento();
                datos[i][7] = alumno.getApoderado().getNombres();
            }
            modelo.setDataVector(datos, nombreColumnas);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        // TODO add your handling code here:
        String nombre=txtbuscarAlumno.getText();

        modelo.setColumnIdentifiers(nombreColumnas);
        try {
            ArrayList<Alumno> lista = AlumnoCN.getInstancia().buscarPorNombre(nombre);
            Object [][]datos=new Object[lista.size()][8];
            for (int i = 0; i < lista.size(); i++) {
                Alumno alumno = lista.get(i);
                datos[i][0] = alumno.getIdAlumno();
                datos[i][1] = alumno.getNombres();
                datos[i][2] = alumno.getApellidos();
                datos[i][3] = alumno.getSexo();
                datos[i][4] = alumno.getTelefono();
                datos[i][5] = alumno.getDireccion();
                datos[i][6] = alumno.getFechaNacimiento();
                datos[i][7] = alumno.getApoderado().getNombres();
            }
            modelo.setDataVector(datos, nombreColumnas);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        txtbuscarAlumno.requestFocus();
    }//GEN-LAST:event_btnTodosActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(dialogBuscarApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(dialogBuscarApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(dialogBuscarApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(dialogBuscarApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                dialogBuscarApoderado dialog = new dialogBuscarApoderado(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtbuscarAlumno;
    // End of variables declaration//GEN-END:variables
}
